---
rig: { name: rig, templimit: 75 }

wallets:
    - &zec t1UzAvKXK6iiLZHPxzVTDZKuJ4juJbpVVcA
#    - &zec zcTxY1kPSjzFPT42PKF9KTGgECMr5wbzrpzwWoDTeK91Dgu82Ybz9VbghsLMd3xMyXL1jQj5knmmNecRpWCHFyZNtfyDtG6
    - &eth !!str 0x5BfcF35f33420b020e5d2f0A3d6152534d03305d
    - &btg GdYm1azonsyC57TZeh9tPx4ynXkrgojq2i
    - &SuprNova dmi3s
    - &binance zng4cWJhBRFKZadZ3zKoLfykAvs3j2hS71s
    - &binance-xvg DSTaZtA3q8PUEhAjNXT5UMUYEtPdvoppB9

miners:
    - &ewbf
        bin:  .local/share/ewbf-v0.3.4b/miner
        args: >
          --server $server --port $port --user $wallet.$name
          --templimit $templimit --fee 0 --eexit 1 --solver 0 --pass $pwd
    - &bminer
        bin:  .local/share/bminer-v6.0.0-d111154/bminer
        args: -uri ${scheme}://${wallet}@${server}:${port}
    - &ethminer
        bin:  .local/share/ethminer-v0.14.0/ethminer
        args: -U -P ${scheme}://${wallet}@${server}:${port}
    - &ccminer
        bin:  .local/share/ccminer-v2.3-tpruvot/ccminer
        args: -o ${scheme}://${server}:${port} -u ${wallet} -p ${pwd} ${extra_params}

pools:
    - &zpool-ca-xvg-scrypt
        wallet:  *binance-xvg
        server:  scrypt.mine.zpool.ca
        port:    3433
        pwd:     !!str c=XVG,scrypt
        scheme:  stratum+tcp
        extra_params: !!str --algo=scrypt --intensity=26 --max-temp=75
    - &zpool-ca-xvg-lyra2z
        wallet:  *binance-xvg
        server:  lyra2z.mine.zpool.ca
        port:    4553
        pwd:     !!str c=XVG,lyra2z
        scheme:  stratum+tcp
        extra_params: !!str --algo=lyra2z --intensity=26 --max-temp=75
    - &zpool-ca-xvg-lyra2v2
        wallet:  *binance-xvg
        server:  lyra2v2.mine.zpool.ca
        port:    4533
        pwd:     !!str c=XVG,lyra2v2,d=280
        scheme:  stratum+tcp
        extra_params: !!str --algo=lyra2v2 --intensity=22.75 --max-temp=75 
    - &flypool
        wallet:  *zec
        server:  eu1-zcash.flypool.org
        port:    3333
        pwd:     2000
        scheme:  stratum
        pwd:     x
    - &ethermine
        wallet:  *eth
        server:  eu1.ethermine.org
        port:    5555
        scheme:  stratum+ssl
    - &gold
        wallet:  *btg
        server:  eu.pool.gold
        port:    3044
        scheme:  stratum
    - &SuprNova-btg
        wallet:  *SuprNova
        server:  btg.suprnova.cc
        port:    8816
        scheme:  stratum
        pwd:     x
    - &SuprNova-zen
        wallet: *SuprNova
        server:  zen.suprnova.cc
        port:    3618
        scheme:  stratum
        pwd:     x
    - &SuprNova-zcl
        wallet: *SuprNova
        server:  zcl.suprnova.cc
        port:    4042
        scheme:  stratum
        pwd:     x
    - &ZenMiningPro
        wallet: *binance
        server:  eu.zenmine.pro
        port:    9009
        scheme:  stratum
        pwd:     x
        
tasks:
    - &zec-ewbf
        miner: *ewbf
        pool:  *flypool
    - &zec-bminer
        miner: *bminer
        pool:  *flypool
    - &eth-ethermine
        miner: *ethminer
        pool:  *ethermine
    - &btg-ewbf
        miner: *ewbf
        pool:  *SuprNova-btg
    - &zen-ewbf
        miner: *ewbf
        pool:  *SuprNova-zen
    - &zen-ewbf-mpro
        miner: *ewbf
        pool:  *ZenMiningPro
    - &zcl-ewbf
        miner: *ewbf
        pool:  *SuprNova-zcl
    - &xvg-zpool-ca-lyra2v2
        miner: *ccminer
        pool:  *zpool-ca-xvg-lyra2v2
    - &xvg-zpool-ca-lyra2z
        miner: *ccminer
        pool:  *zpool-ca-xvg-lyra2z
    - &xvg-zpool-ca-scrypt
        miner: *ccminer
        pool:  *zpool-ca-xvg-scrypt

#main:  *xvg-zpool-ca-x17
#main: *xvg-zpool-ca-scrypt
#main: *xvg-zpool-ca-lyra2z
#main: *xvg-zpool-ca-lyra2v2
main: *zec-ewbf
#main: *zcl-ewbf
